macports/macports-base

src/macports1.0/macports.tcl, src/pextlib1.0/Pextlib.c, src/pextlib1.0/uid.c, src/pextlib1.0/uid.h
These changes improve handling of a ports tree with git. Exporting HOME and SSH_AUTH_SOCK ensures that git can read its configuration and is able to access SSH keys if necessary.
Review-Request: @jmroot @neverpanic
=> Improve use of UpdateVCS with git

src/macports1.0/tests/macports.test
The expected output for those functions changed with the commits
- 42a88e507ae9035a759225dd2779f3301865c664 and
- 08a845ff322d4f1ab55d2fcf53ecb5970d63db57.
Fix the tests to pass again.
Review request: @raimue, @jmroot.
=> tests: Fix git version control updating tests

src/macports1.0/macports.tcl, src/macports1.0/tests/macports.test
Apple's /usr/bin/git returns additional information at the end of the
standard Git version string, so that splitting at whitespace and using
the last component does not yield the expected version number.
Fix this by using a regex instead and adjust the tests to test both
cases.
For reference: The string returned by /usr/bin/git looks similar to
| git version 2.9.3 (Apple Git-75)
=> Fix version detection with Apple Git, adjust tests

src/macports1.0/macports.tcl, src/macports1.0/macports_util.tcl, src/macports1.0/tests/macports_util.test, src/port/port.tcl, src/port1.0/portutil.tcl, src/port1.0/tests/portutil.test
We have two equal implementations of unobscure_maintainers, but only
a single one should exist. Move the implementation to the macports_util
package where it can be used by port(1) and port1.0, adjust uses in
port(1), drop the implementation from port1.0, because it is unused.
Additionally, add a test that verifies that @github-username works as
expected in base. Note that no changes in the code are required to
support this.
Review request: @macports/portmgr, @mojca, @larryv.
=> Support multi-valued maintainers

Makefile.in, configure.ac, src/Makefile.in, src/macports1.0/macports.tcl, src/macports1.0/macports_util.tcl, src/mpcommon1.0/Makefile.in, src/mpcommon1.0/mpcommon.tcl, src/mpcommon1.0/signalcatch.tcl, src/port1.0/port.tcl
The addition of Tclx signal handlers means that SIGINT and SIGTERM
now result in an error being raised. In most places where the catch
command is used, we don't actually check if the error is a signal, and
in most of those cases can't do anything sensible except re-raise the
error anyway.
Thus we replace 'catch' with our own version which encapsulates
checking if the error is a signal and (by default) re-raises it if so.
The -signal flag can be passed as the first argument to the new catch
to make it catch signals too.
The code is sourced from its own file in both the main interpreter
and the slave interpreters that execute Portfiles. It can't simply be
aliased in to the slaves like we normally do for shared commands
because it uses uplevel and aliases add an extra call level.
=> Use a 'catch' wrapper that can ignore signals

src/port/port.tcl
After 30c27d5d3ad169ffa5f55465cf9663dbd1ff7537, the output of `port info` for maintainers is broken for some cases. This tries to resemble the old output of 2.3.4 as closely as possible.
While I am at it, also fix the output for long_description that should not contain multiple lines unless the output is pretty-printed.
See: https://trac.macports.org/ticket/52928
Review-Request: @neverpanic
=> Fix 'port info' output for maintainers and long_description

portmgr/dmg/postflight.in
The postflight script was using the SHELL variable, which is root's shell
and not USHELL, which is the user's shell.
The test for MacPorts paths in the users PATH can be made more robust.
The old code will match on /opt/locale for example.
Spit the PATH into one path per line with tr and then grep for an exact match
with /opt/local/bin.
=> Fix the detection of /opt/local/bin in user's PATH

portmgr/dmg/postflight.in
Replace all cases of ${USHELL} -l with /usr/bin/su commands.
First use is commented explaining each steps purpose.
Use printenv VAR | tail -n 1 to make sure that only the VAR's value is passed on.
It is not uncommon for profiles to print information to stdout.
Refactor the MANPATH logic to use su and the tr|grep idium to look at for a path.
Delete all the logic for DISPLAY as its not required in any supported macOS
version that MacPorts supports.
Replace hardtab with spaces
=> Never run installing user's profile code as root

doc/port-reclaim.1, doc/port-reclaim.1.txt, doc/port.1, doc/port.1.txt, src/macports1.0/reclaim.tcl, src/port/port.tcl
`port reclaim` is quite nice for cleaning up waste, but it doesn't do anything about ports you no longer need, such as build dependancies — like `apt-get` and its `autoremove`. To work around this, I'd occasionally do repeated `port uninstall leaves` until no such leaves were left — which is a bit silly…
This pull request attempts to address this in two different ways. The first commit adds an `rleaves` alias which identifies all unrequested ports. The seconds commit achieves the same within `port reclaim`.
I considered extending `leaves` to list _all_ proper leaves — but opted not to, in the interest of backwards compatibility.
=> Make uninstalling unnecessary ports easy

src/port1.0/portlivecheck.tcl
For livecheck regex all we are interested in is the version numbers.  To avoid to have to match all cases in livecheck.regex, this patch adds -nocase.  There are many ports where the name/distname/website have different cases which makes livecheck time-consuming with adding non-default regexps.
=> livecheck: add -nocase to ignore all cases in regexp

src/port/port.tcl, src/port1.0/fetch_common.tcl, src/port1.0/portfetch.tcl
This flag avoids adding the mirrors defined by global_mirror_site to the
list of fetch URLs. This is meant to aid in development of port updates.
No mirror will have a distfile for a new port version, so there is no
need to try.
=> New argument port fetch --no-mirrors

src/port/port.tcl
Add conjunctions to allow easier understanding of license info.  This
avoids the issue of having to remember what licenses in {} and those
without {} mean.
Examples listed below: top line is current, 2nd line is with patch
cfitsio license: zlib MIT {LGPL Noncommercial}
cfitsio license: zlib and MIT and (LGPL or Noncommercial)
rust license: {MIT Apache-2} BSD zlib NCSA Permissive
rust license: (MIT or Apache-2) and BSD and zlib and NCSA and Permissive
edb license: BSD BSD-old Sleepycat
edb license: BSD and BSD-old and Sleepycat
qt55 license: {LGPL-2.1 LGPL-3 GPL-3 OpenSSLException}
qt55 license: (LGPL-2.1 or LGPL-3 or GPL-3 or OpenSSLException)
Others to look at: itext, dmd-bootstrap, libgdiplus
=> Expand license output by adding '(' 'or' ')' 'and' between licenses

src/port1.0/portsandbox.tcl, tests/test.tcl.in, tests/test/setuid/DESCRIPTION, tests/test/setuid/Portfile, tests/test/setuid/files/test.sh, tests/test/setuid/test.tcl
Closes: https://trac.macports.org/ticket/54963
After merging this, we should also cherry-pick these commits to release-2.4 and release 2.4.2 for High Sierra.
=> Ports cannot set setuid bit on High Sierra

doc/macports.conf.5, doc/macports.conf.5.txt, doc/macports.conf.in, doc/portfile.7, src/port1.0/portstartupitem.tcl
Tiger introduced launchd and is the earliest OS that macports supports.
This removes the obsolete startupitem_type SystemStarter.
see https://trac.macports.org/ticket/36770
=> startupitem_type: remove SystemStarter

src/cregistry/entry.c, src/cregistry/entry.h, src/cregistry/sql.c, src/pextlib1.0/Pextlib.c, src/pextlib1.0/Pextlib.h, src/pextlib1.0/tracelib.c, src/registry2.0/entry.c, src/registry2.0/receipt_flat.tcl, src/registry2.0/receipt_sqlite.tcl, src/registry2.0/registry.tcl
While updating `ghc` in trace mode, I noticed it failing while including `"GC.h"`. `ghc` actually meant to include a file named `GC.h` from its own source tree, but due to providing `-I${prefix}` before include directives for its own source tree, `/opt/local/include/gc.h` was picked by the compiler.
On a case-sensitive system, this wouldn't have happened.
Ultimately, the build process was able to read `/opt/local/include/GC.h`, even though `ghc` did *not* depend upon `boehmgc`, but eventually failed to build as it wasn't able to read `/opt/local/include/gc/gc.h`. Curiously, both files *should* have belonged to the same port (`bohemgc`.) However, `port provides /opt/local/include/GC.h` returned no registered port for this file - which was also queried as such by trace mode and thus allowed …
=> misc: let 'port provides' and trace mode honor the FS case-sensitivity.

src/port1.0/portlint.tcl
Currently, port lint only finds PortGroups that start on first column.
A large number of ports have PortGroup lines indented due to ifs.
Note: lint displays multiple identical PortGroup groups as an error.
=> port lint: allow spaces before PortGroup lines

doc/macports.conf.5, doc/macports.conf.5.txt, doc/macports.conf.in, doc/portfile.7, src/port1.0/portstartupitem.tcl
Remove non-darwin startupitem_type rcng.  As far as I can tell, it hasn't worked in a long time since it was committed in 2005.    It is missing the etc/rc.subr which contains the script needed for the rc scripts to run.  If this is needed later, it would be better to start from scratch using a new version of rc scripts.
see https://trac.macports.org/ticket/36770
=> Remove rcng startupitem type

src/pextlib1.0/Pextlib.c, src/pextlib1.0/Pextlib.h
A function written like `void foo()` is actually a C89 style
non-protoype declaration. Change this to ensure that the function is
only called with zero arguments.
=> Fix prototype for new_mount_cs_cache

src/pextlib1.0/tracelib.c
Keeping the list of dependencies sorted allows using binary search when
determining whether a file is provided by a port in the dependency tree.
Depending on the length of the list of dependencies, this can yield
build time improvements of around 10 %.
Additionally, use Tcl's list functions to interpret the list of
dependencies rather than splitting at whitespaces manually.
=> base: tracelib: Use binary search in dep_check()

vendor/Makefile.in
In the current version, trying to running `make install DESTDIR=/foobar` as a normal user (with write permissions to /foobar) results in permission errors.
The DESTDIR approach is used in my [Arch Linux personal package](https://aur.archlinux.org/packages/macports-base-git/). I'm going to run version checks as a daily cron job on my Linux server.
=> Fix `make install DESTDIR=/foobar`

aclocal.m4, autogen.sh, configure, configure.ac, src/config.h.in, src/darwintracelib1.0/readlink.c, src/port1.0/port_autoconf.tcl.in, src/port1.0/portutil.tcl
- GNU sed has supported -E for a long time. In addition, `-E` has been
POSIX since 2012.  http://austingroupbugs.net/view.php?id=528#c1112
- readlink has been in POSIX even longer. Removal of this check breaks
macOS 10.3 and lower.
This is already broken in configure
```
31   10.0*|10.1|10.1.*|10.2*|10.3*)
32     AC_MSG_ERROR([This version of Mac OS X is not supported
```
- While here, change autogen.sh to use autoreconf
=> Further assume we're on a POSIX system

src/port1.0/portutil.tcl
Instead of assuming the ccache binary is provided by the ccache port,
query the registry which port provides ${prefix}/bin/ccache if it exists
and also include all dependencies.
Closes: https://trac.macports.org/ticket/55680
=> Find port providing ccache binary for trace mode

doc/port.1, doc/port.1.txt
Update year range from 2004-2012 to 2004-2017
under AUTHORS for port man page.
Change the from branch to separate branch instead of fork/master. 
Replaces PR #50
=> Update year in AUTHORS for port man page

src/port1.0/portmirror.tcl
Use this license to prevent mirroring of ports which license does not
allow to host their distfiles on our servers.
=> port mirror: Respect special license NoMirror

src/macports1.0/reclaim.tcl, src/port/port.tcl
This patch eliminates the possibility for the user to choose which
unrequested/inactive port to remove in the reclaim phase. Now the user
can either remove all ports on none at all.
This was done so we can safely force-remove all ports and avoid asking
confirmation to the user.
=> reclaim.tcl: don't ask for partial removal

src/port1.0/portconfigure.tcl
PPC cannot use clang-3.3 or clang-3.4 successfully
fallback to gcc6 or gcc7 if default compilers are
blacklisted
fixes innumerable tickets to be closed individually
I hope I've done this correctly - it's my first base PR.
=> portconfigure: fix compiler selection on PPC

src/macports1.0/macports.tcl, src/port/port.tcl, src/port/portindex.tcl, src/port1.0/portdepends.tcl, src/port1.0/portlint.tcl, src/port1.0/portutil.tcl
This can be used to handle xz patches in the below trac ticket (which
requires another patch to base).
See https://trac.macports.org/ticket/52445
=> Add depends_patch to handle the patch dependencies of ports

src/macports1.0/reclaim.tcl
Do not ask questions in non-interactive mode (-N), but still run all the
checks and remove ports and files by default. Do not delete any files in
dry-run mode (-y), even if the user confirmed the removal.
Closes: https://trac.macports.org/ticket/53857
---
@g5pw Sorry for hijacking the ticket assigned to you, but my system was in the need of a cleanup, so I went ahead and implemented this.
=> reclaim: Respect -N and -y flags

src/compat/strlcpy.c
The typo prevents building on Linux
```
cc -c -DUSE_TCL_STUBS -DTCL_NO_DEPRECATED -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -Wextra -Wall -pedantic  -D_FORTIFY_SOURCE=2 -DHAVE_CONFIG_H -I/build/macports-base-git/src/macports-base/src -I/build/macports-base-git/src/macports-base/src -I. -I/build/macports-base-git/src/macports-base/vendor/vendor-destroot//opt/local/libexec/macports/include -fPIC strlcpy.c -o strlcpy.o
strlcpy.c:38:10: fatal error: strlcopy.h: No such file or directory
#include "strlcopy.h"
^~~~~~~~~~~~
compilation terminated.
```
=> Fix a typo

src/pextlib1.0/Pextlib.c
```
Pextlib.c:956:33: warning: missing field 'st_mode' initializer [-Wmissing-field-initializers]
struct stat path_stat = { 0 },
^
```
I am not even sure why clang emits this warning at all, but I could also reproduce it with a minimal example. An alternative could be to use `struct stat s = {};`, but that is non-standard.
In case of `struct stat`, manual initialization should not be necessary as it is passed to `stat(2)`, which will set all fields.
@Ionic As you wrote this, I would appreciate a review.
=> pextlib: Fix -Wmissing-field-initializers warnings

doc/portfile.7, src/port1.0/portextract.tcl, src/port1.0/portfetch.tcl
In the interest of trying to reduce the number of ports that need to override the options of the extract phase, this PR introduces a new `use_tar` option. A separate PR will be sent to macports-ports to update the ports that currently manually implement this functionality.
=> Add use_tar option

src/port/portindex.tcl
I extracted the changes to `portindex` only from #63. These changes are safe to be merged in this form and do not require additional changes to our infrastructure generating the PortIndex (in mprsyncup).
This ensures we are using the default cxx_stdlib value when generating a PortIndex for older systems.
This is meant to be merged now so it can be released with MacPorts 2.5.0. The rest of the corresponding ticket, involving coordinated changes to mprsyncup and base, can be addressed afterwards.
See: https://trac.macports.org/ticket/55471
=> portindex: support creating PortIndex for libc++ (portindex only)

doc/Makefile.in, src/darwintracelib1.0/Makefile.in, src/machista1.0/Makefile.in, src/macports1.0/Makefile.in, src/mpcommon1.0/Makefile.in, src/package1.0/Makefile.in, src/pextlib1.0/Makefile.in, src/port/Makefile.in, src/port1.0/Makefile.in, src/registry2.0/Makefile.in
This fixes the `install_name` of the darwintrace1.0, machista1.0 and macports1.0 plugins. There was already code in the pextlib1.0 Makefile to set the `install_name` which I copied to the other Makefiles.
The registry2.0 plugin uses an `install_name` containing `@loader_path` and this PR doesn't change that. This is needed to prevent a build failure when MacPorts is not already installed, because the pextlib1.0 plugin links with the registry2.0 plugin as a library. See 5f7e3d27bcd8643c820cacd9c6883980ff2298eb.
The `install_name` of the other plugins doesn't technically matter, but it is tidier to set it correctly, especially on Tiger where otherwise a randomly-generated temporary filename is used as the `install_name` (see https://trac.macports.org/ticket/37867).
I removed the space after …
=> Fix plugin install names

src/cregistry/Makefile.in
allows cregistry Makefile.in  to respond to
--with-sqlite3prefix
similarly to registry2.0 Makefile.in
=> cregistry: add SQLITE3 flags

src/port1.0/portfetch.tcl
When MacPorts attempts to fetch from DropBox, it gets HTML instead of the requested file.  This is because MacPorts sets curl's User-Agent header to a non-default value. The problem was first [reported by Mojca](https://trac.macports.org/ticket/53942) in regard to port audio/generaluser-soundfont.
This PR simply hardcodes a default value for userAgent in curl.c.  Doing so allows audio/generaluser-soundfont to fetch without a custom fetch block.
=> curl.c: User-Agent should default to "curl/version"

src/port1.0/porttrace.tcl
Apple has a nasty habit of nuking folders when something is updated, which means it isn't really safe to store older SDKs in the Developer folder.
So, what does this do?
Considering macports supports pointing to a non-default SDK via ```configure.sdkroot``` (which is very necessary if one is building binaries meant to be bundled and shared), I made sure running in trace-mode includes that folder, for the cases when it is not under the Developer folder.
=> port1.0: Include non-default SDK in trace sandbox.

src/pextlib1.0/readline.c, src/port/port.tcl
As per the discussion [here.](https://trac.macports.org/ticket/56381) Please let me know if you have any improvements in mind. Pinging @raimue since we spoke about this together on the aforementioned Trac ticket.
=> Append history in interactive sessions

src/port1.0/portlint.tcl
As per discussion in macports/macports-guide#21
=> port lint: warn if checksum section is missing file size field

src/port1.0/portchecksum.tcl, src/port1.0/portlint.tcl, src/port1.0/tests/portchecksum.test, src/port1.0/tests/portlint.test
This PR builds upon discussion originating in macports/macports-guide#21, and work started in #101.
The changes here make `port lint` perform a much more thorough vetting of checksum stanzas in Portfiles.
Any checksum type that isn't part of the canonical list specified in `portchecksum` is counted as an error, as well as any unrecognized field or token.  (This will also catch situations where a filename is hanging without any checksums specified for it, erroring out.) . Errors also happen when a particular checksum does not resemble its specified type (ie., md5 1234).
In the case of deprecated checksum types, warnings are issued.  Warnings are also issued in the case that a set of checksums does not include the current set of recommended checksum types (sha256, rmd160 & size, also as per …
=> port lint: lint checksums much more thoroughly

src/pextlib1.0/curl.c, src/port1.0/portlivecheck.tcl
See
https://trac.macports.org/ticket/56975
src/pextlib1.0/curl.c : Add --append-http-header option to allow custom HTTP headers to be appended to fetches.
src/port1.0/portlivecheck.tcl : Add new livecheck.curloptions options to allow additonal options to be passed to the curl fetch. Default is :-
```
{{ "--append-http-header" "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" }}
```
=> Add option to pass custom Header to curl fetch

src/pextlib1.0/fs-traverse.c, src/pextlib1.0/tests/fs-traverse.tcl, src/port1.0/portextract.tcl
This attempts to resolve an [issue raised by Mojca](https://github.com/macports/macports-ports/pull/1075#discussion_r154493451) where worksrcdir has to be set manually if a source archive extracts to an unexpected directory.  In this particular case, for instance, the archive is named v2.4.1.tar.gz and extracts to libwebsockets-2.4.1.
Similarly, using the github.setup defaults, the archive (tagged as v2.4.1) is libwebsockets-2.4.1.tar.gz and extracts to warmcat-libwebsockets-e4e774b.
=> If expected path of extract doesn't exist, symlink to actual path.

src/cregistry/entry.c, src/cregistry/entry.h, src/registry2.0/entry.c, src/registry2.0/tests/entry.tcl
entry_search had a "type confusion" bug where it would perform array accesses that bypassed bounds checks if given arguments that looked like strategies. I've rewritten most of the argument parsing loop in a way that should eliminate this issue, while being shorter and more straightforward (with less duplicated code), only requiring one pass through the arguments. The downside is that we allocate a bit more memory and have a couple of gotos to handle errors.
You can reproduce this crash with `port install [some port name] --`, if you'd like to test it. If there's something stylistically wrong with my pull request, please feel free to let me know–I'm not completely sure how you'd like it formatted.
=> Fix a crash due to an out-of-bounds array access

src/port1.0/porttrace.tcl
“tracelib" is a command being used majorly in the file.
"tracelib" is also being used as a variable name.
Renamed “tracelib" variable to “darwintracepath" to make code more understandable.
=> porttrace.tcl: renamed variable tracelib and corrected misspelled “thred” to “thread"

src/pextlib1.0/tracelib.c
if ((kev.flags & EV_ERROR) == 0 || ((kev.flags & EV_ERROR) > 0 && kev.data != 0))
If compilers find first operand true while evaluating || , the second operand isn’t checked.
So the second operand is only checked if (kev.flags & EV_ERROR) != 0.
So (kev.flags & EV_ERROR) > 0 it doesn’t need to be checked in conjunction with kev.data != 0.
It doesn’t return negative as its of type uint16_t.
=> tracelib.c: Removed unnecessary condition in if

src/port/port.tcl
e05bba0f867a9ef88d80a97678a34c6a1bf0a3ce added a "Nothing to upgrade"
message when doing a 'port upgrade outdated' and returned an error.
This changes the return value to a non error.
closes https://trac.macports.org/ticket/58309
=> Do not return an error if there's no ports to upgrade

src/port/port.tcl
Currently due to the use of 'array names', the output of
'port info --multiple-fields' are displayed in a random order.
Now, the fields are kept in a list which preserves their order they
were given on the command line.
This has the effect of also allowing duplicate fields to be displayed.
Closes: https://trac.macports.org/ticket/57003
=> port-info: output fields in the order given on the command line

aclocal.m4, configure
This came up in discussion on [pull request #86](https://github.com/macports/macports-base/pull/86#discussion_r186274970).
Should we also do the same for the other variables listed in `./configure --help`?
```
Some influential environment variables:
CC          C compiler command
CFLAGS      C compiler flags
LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
nonstandard directory <lib dir>
LIBS        libraries to pass to the linker, e.g. -l<library>
CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
you have headers in a nonstandard directory <include dir>
CPP         C preprocessor
```
=> configure: Pass the selected $CC to vendor sources

src/port/port.tcl, src/port1.0/Makefile.in, src/port1.0/port.tcl, src/port1.0/portbump.tcl
This is still a WIP, part of my GSOC 2019 proposal. Any feedback is greatly appreciated
Backlog:
For context: the `port bump` action would bump Portfile version and checksums as requested here: https://trac.macports.org/ticket/53851
My current implementation is a "bump" stage which requires the "main" and "fetch" stages to be
sucessfully run first. portbump.tcl largely reuses code from portchecksums.tcl. The desired output is something like this:
```
$ port bump
--->  Fetching distfiles for chromedriver
--->  Verifying checksums for chromedriver
Old sha256: 00b6ac50b0de0bd63d260cc7472c6e6af44b1240
New sha256: 2aa256d17e4b2cc21f888b0e1b9ed211b925bf40
Old size: 6809243
New size: 7057233
Do you approve of these changes [Y/n]? Y
Do you want to reset revision number (currently 2) to 0 [Y/n]? Y …
```
=> port1.0: add portbump.tcl

configure, configure.ac
This PR updates the configure check for supported macOS versions with two fixes:
* The initial version of each major macOS version (e.g. "10.7" or "10.13") is now recognized. Previously we were checking for e.g. "10.7.0" or "10.13.0" but Apple does not use a trailing ".0" for initial macOS versions and the output of `sw_vers -productVersion` reflects that.
* macOS Mojave 10.14-10.14.4 are recognized as outdated while later versions are recognized as supported.
=> Update configure check for supported macOS versions

src/port1.0/portutil.tcl
* ~~Changes message from “most ports” to “some ports”. This has been requested.~~
* ~~Warn only once every two weeks. This solves the complaint that the warning spams the terminal (e.g when doing `sudo port upgrade`).~~
* Remove warning since we already error out on Xcode-dependent ports.
References https://trac.macports.org/ticket/35045
References https://trac.macports.org/ticket/58016
=> Remove Xcode uninstalled warning message

src/port1.0/portutil.tcl
* refactor autoreconf, automake etc to one loop
* export DEVELOPER_DIR for destroot, build, and autotools
Since we're hiding Xcode on trace mode if ports aren't Xcode-dependent, ports that do e.g `post-build { system -W "someotherdir" "make" }` fail because `/usr/bin/make` resolves to Xcode's make. It should resolve to CommandLineTools's make instead like `build.cmd make` already does.
This PR solves that problem by also setting DEVELOPER_DIR for build, destroot and all the autotools.
=> Universally export DEVELOPER_DIR

src/port1.0/portconfigure.tcl, src/port1.0/portmain.tcl, src/port1.0/porttrace.tcl
- move xcrun --sdk macosx to find macOS SDK to the top
- export DEVELOPER_DIR so xcrun can find CommandLineTools SDK
Relevant: https://trac.macports.org/ticket/57143
`xcrun --sdk macosx`, which was previously reenabled as the final fallback by @jmroot, is moved to the top of the `::configure_get_sdkroot` proc so the newest-available macOS SDK is returned first instead of the current OS version's SDKs. It was generally agreed on trac that the newest-available SDK should be used, so I assume this change is better and causes no problems.
[previously reenabled]: https://github.com/macports/macports-base/commit/8caac195a15c8a01d07cf337439fd68f4370d9ee
The DEVELOPER_DIR change is done so a CommandLineTools SDK is returned if the port isn't Xcode-dependent. This fixes gmp failing to install in …
=> portconfigure: Prioritize returning SDK with DEVELOPER_DIR set 

src/port1.0/portutil.tcl
Doesn't work yet. We want to fix `system -W` resolving to Xcode binaries which we now hide in tracemode if the port isn't Xcode-dependent. Ports like libnetpbm, tig, and emacs now fail to install in tracemode because of this.
I've said in the mail that it was around 60 ports that use system -W, but there's actually 357 matches for system -W in macports-ports, which would be a headache to patch since we don't know which ones might resolve to an Xcode tool.
Is this the wrong way to do it? It works with exec, I'm naively assuming it'd be the same for system.
```tcl
% set ::env(DEVELOPER_DIR) /Library/Developer/CommandLineTools/
/Library/Developer/CommandLineTools/
% exec clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: …
```
=> portutil: Export DEVELOPER_DIR for target {} blocks

src/port1.0/portconfigure.tcl
clang-3.9 and clang-4.0 have been obsoleted, in favour of clang-8.0.
```
> port info clang-3.9 clang-4.0
clang-3.9 @3.9.1_10 (lang)
Replaced by:          clang-8.0
Description:          This port has been replaced by clang-8.0.
Homepage:             https://www.macports.org
Platforms:            darwin
License:              NCSA
Maintainers:          Email: jeremyhu@macports.org, GitHub: jeremyhu
Email: larryv@macports.org, GitHub: larryv
--
clang-4.0 @4.0.1_7 (lang)
Replaced by:          clang-8.0
Description:          This port has been replaced by clang-8.0.
Homepage:             https://www.macports.org
Platforms:            darwin
License:              NCSA
Maintainers:          Email: jeremyhu@macports.org, GitHub: jeremyhu
Email: larryv@macports.org, GitHub: larryv
```
consequently …
=> clang 3.9, 4.0 have been obsoleted, in favour of clang 8.0, so remove from fallback

src/port1.0/portconfigure.tcl
backport changes in https://github.com/macports/macports-base/pull/137 to the 2.5.x branch.
=> Remove reference to MP clang 3.9 and 4.0

src/port1.0/porttrace.tcl
```
Warning: The following existing file were hidden from the build system by trace mode:
/var/db/timezone/zoneinfo/Asia/Jakarta
```
When installing 261 ports with tracemode, this message popped up [232] and [233] times respectively on 10.13 w/o Xcode and 10.14 w/ Xcode.
`/var/root/.CFUserTextEncoding` also popped up, but I don't know if that's as harmless as timezone.
[232]: https://paste.macports.org/8d4a12615e02
[233]: https://paste.macports.org/ba4702689b08
=> porttrace: allow /var/db/timezone/zoneinfo/

src/macports1.0/macports.tcl, src/port1.0/portutil.tcl
* repeat _check_xcode_version in _mportexec
* add portname in _check_xcode_version error message
Error out earlier if dependency needs Xcode.
Current behavior:
```
$ sudo port install gnuplot
--->  Computing dependencies for gnuplot
The following dependencies will be installed: 
aquaterm
libcaca
libcerf
lua
wxWidgets-3.0
wxWidgets-common
wxWidgets_select
Continue? [Y/n]: Y
--->  Fetching distfiles for aquaterm
--->  Verifying checksums for aquaterm
--->  Extracting aquaterm
--->  Applying patches to aquaterm
--->  Configuring aquaterm
--->  Building aquaterm
Error: Failed to build aquaterm: command execution failed
Error: See /opt/local/var/macports/logs/_aqua_aquaterm/aquaterm/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: …
```
=> macports.tcl: repeat xcode check for dependencies

src/port/port.tcl
If quiet mode is active, suppress the old PortIndex warning in order to
avoid these spurious warnings in non-interactive scripts such as the
bash-completion helper.
See: https://trac.macports.org/ticket/58452
=> port: Suppress old PortIndex warning in quiet mode

src/macports1.0/macports.tcl, src/port1.0/portutil.tcl
We don't need to check the Xcode version (or presence) if we're not going to build a port from source. This was previously achieved with a shortcut in `_check_xcode_version` that would always return 0 if an archive was available.
This fixes a situation where `_check_xcode_version` would indicate Xcode isn't required because an archive is available even though a user specifically asked for a build from source (e.g. when running 'sudo port destroot' on a port that sets `use_xcode yes`).
The newly introduced `_target_needs_toolchain` now returns `yes` for all cases where a toolchain is required regardless of archive availability and returns `yes` iff an archive is available for those targets that only need a toolchain when no prebuilt archive is being used.
Tested by applying these …
=> macports1.0: Only check Xcode if building from src

src/port1.0/porttrace.tcl
`/var/db/mds/system` is used when loading the system certificate store, so allow it in trace mode. This fixes trace mode builds using the haskell stack build system, which downloads things during the build phase.
Additionally, remove a trailing slash from the entry for `/var/db/timezone/zoneinfo`, which seems to have prevented it from working correctly.
=> port1.0: Allow /var/db/mds/system in trace mode

src/port1.0/fetch_common.tcl
Correctly add multiple URLs specified in `archive_site_local`, `master_site_local`, and `patch_site_local` when a tag is used.
Closes: https://trac.macports.org/ticket/57718
=> Fix archive_site_local, master_site_local, patch_site_local when multiple URLs are specified

src/darwintracelib1.0/darwintrace.h
On calling `debug_printf(format, …)`  if no variable args are passed, the current definition of the macro would cause errors.
Using ##__VA_ARGS__ would handle such a scenario by removing the trailing comma.
=> use ##__VA_ARGS__ instead of __VA_ARGS__

src/port1.0/portconfigure.tcl
No Apple clang can build on 10.6.8 against libc++
only macports-clang-* compilers will so so
This fixes my corner case where I used Xcode 4.2 with MacPorts 2.6 on 10.6.8, and portconfigure.tcl was returning "clang" for the compiler (which failed).
=> don't use Apple clang if libc++ on 10.6.8

src/port1.0/portbump.tcl
Fixes error 'both_checksums": no such variable' when there are no
checksums lines in the Portfile prior to a 'port bump'.
=> bump: Error out if checksums lines are missing from Portfile

src/macports1.0/macports.tcl
Tcl defaults to running unknown commands in a shell automatically. This can inadvertently lead to running things in the shell instead of using a Tcl builtin, e.g. due to a typo.
It does not seem like we are currently using this functionality, and we really shouldn't, so disable it on startup to ensure it is not used.
=> mportinit: Disable running unknown cmds in $SHELL

portmgr/dmg/postflight.in
Apple switched the default Shell on macOS Catalina to zsh, so our installer now no longer correctly configures $PATH in the default configuration.
Add support for zsh to fix this. Write the PATH configuration to `~/.zshenv`, which seems to be the default location for this kind of configuration data on zsh.
=> postflight: Support zsh

src/port1.0/portconfigure.tcl
Ports that specify `compiler.cxx_standard 2014` fail on OS X 10.9 (see https://trac.macports.org/ticket/59323 or https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/107245) because its clang 600.x.x gets used, even though only clang 602 and later support C++14 (see https://trac.macports.org/ticket/57682).
=> Fix C++14 minimum clang version

src/pextlib1.0/curl.c, src/pextlib1.0/tests/curl.tcl
This closes https://trac.macports.org/ticket/55011 .
=> Enable cURL's automatic decompression

src/port1.0/portmain.tcl, src/port1.0/portutil.tcl
Setting CC_PRINT_OPTIONS and CC_PRINT_OPTIONS_FILE changes how Clang
handles the compiler flags -v and -Wl,-v.
If a port relies on the default behavior (e.g. FindOpenMP in CMake),
then errors can ensue.
=> allow Portfile to turn off verbose logging

src/port1.0/portconfigure.tcl
`clang++-mp-X.Y -fopenmp ...` links against libraries in libomp.
=> add libomp  library dependency with OpenMP and Clang

src/port1.0/portconfigure.tcl
See https://lists.macports.org/pipermail/macports-dev/2019-November/thread.html#41503
=> restrict compiler for C++11 and thread-local storage

src/port1.0/portconfigure.tcl, src/port1.0/portmain.tcl
For many ports, the compiler flags
-I${prefix}/include,
-L${prefix}/lib,
-isysroot${configure.sdkroot}, and
-Wl,-syslibroot,${configure.sdkroot}
are unnecessary because of the environment variables
CPATH,
LIBRARY_PATH, and
SDKROOT.
compiler.limit_flags prevents MacPorts from attempting to add
unnecessary compiler flags, which can cause problems.
See https://trac.macports.org/wiki/CompilerEnvironmentVariables
for details.
=> allow compiler to use environment variables only

src/pextlib1.0/curl.c, src/pextlib1.0/tests/curl.tcl, src/port1.0/portlivecheck.tcl
- Fix build on old MacOS X
- Leave compression OFF by default
- For livecheck, turn it ON by default
- Expose livecheck compression toggle to portfile via livecheck.compression
=> Fixes to HTTP compression behavior

src/macports1.0/macports.tcl, src/package1.0/portarchivefetch.tcl, src/pextlib1.0/system.c, src/port1.0/Makefile.in, src/port1.0/portbuild.tcl, src/port1.0/portconfigure.tcl, src/port1.0/portdestroot.tcl, src/port1.0/portfetch.tcl, src/port1.0/portprogress.tcl, src/port1.0/porttest.tcl, src/port1.0/portutil.tcl
- Parses ninja and cmake makefile output to display determinate progress bars.
- If there's nothing to be parsed (or its been too long since parsing succeeded), switches to an indeterminate progress bar.
=> Basic target progress bar support

src/port1.0/portlint.tcl
The current behavior is to only allow patch-*.diff patchfiles.
Ryan Schmidt's comment on ticket 59695:
The lint warning was originally added to discourage users from adding
patchfiles that had neither the .diff nor the .patch extension, since
that resulted in incorrect syntax coloring in text editors that
determine the filetype from the extension.
closes https://trac.macports.org/ticket/59695
=> Adjust lint --niptick on patchfiles to allow *.diff or *.patch

src/port1.0/portutil.tcl
Currently, only a warning is printed and the processing of the port
continues. This typically results in a port not completing later.
After this patch, an error is printed with the port name added and
then the port processing aborts.
closes https//trac.macports.org/ticket/59787
=> Abort when a port includes a nonexistent PortGroup

src/port1.0/portconfigure.tcl
Minor update to `portconfigure.tcl` to extend the regex used to detect macports provide clang compiler to support the dropping of the minor version from the port name, starting with `clang-10` (https://github.com/macports/macports-ports/pull/6902).
Note that the changes here do not require any changes in the ports tree, either to add the `clang-10` compiler or to the resources to add it to the known lists, so can be applied before they are done. However the changes here are required to be available before `macports-clang-10` can be used as a compiler option.
Once merged I would propose cherry-picking this to the 2.6 release branch, such as to make it available in the next release from that branch.
=> portconfigure: Add support for Macports Clang versions 10+

src/port1.0/portconfigure.tcl
See discussion at
https://github.com/macports/macports-ports/commit/48084021368e430f889a9bb22983ad0716435555
If we want to support this as a possible option (perhaps useful for port maintainers as a testing option), minor changes to base are required to support this.
=> Add support for macports development clang/gcc ports as compiler options

src/port/port.tcl
The install action has always ignored any @version provided on the
command line.  This causes confusion for users so change to abort the
command and force user to remove the @version.
Closes: https://trac.macports.org/ticket/60454
=> For install action, abort if any @version is provided on command line

src/machista1.0/tests/libmachista-test.c
In Catalina 10.15, the output of otool changed.
This fixes the machista1.0 test 'parsing libSystem.B.dylib'.
Library current version mismatch. Expected `83.0.0, reexport', was
`83.0.0'
10.13 example:
/usr/lib/system/libxpc.dylib (compatibility version 1.0.0,
current version 1205.70.15)
10.15 example:
/usr/lib/system/libxpc.dylib (compatibility version 1.0.0,
current version 1738.120.8, reexport)
Tested in 10.13 and 10.15.
Closes: https://trac.macports.org/ticket/60580
=> Fix machinsta1.0 test by removing ', reexport' from the otool output

src/pextlib1.0/tests/curl.tcl
Updating braeburn to a subversion version >= 1.10.0 broke this test, because the subversion backend no longer delivers the `Last-Modified` header.
Switch to a URL under our control that does and, adjust the other tests as required, update the timestamps to check in the `curl isnewer` testcases, and drop unused variables.
Ideally, we wouldn't be relying on a remote server for this test and start a local one, but Apple doesn't ship `/usr/bin/python3` on modern systems, we should probably not rely on `/usr/bin/python` being around for very much longer, and I'm not aware of any other quick-and-dirty
webservers we could start for the test short of writing our own.
Closes: https://trac.macports.org/ticket/60630
=> tests: Fix curl isnewer test broken by braeburn update

src/pextlib1.0/curl.c
curl < 7.60.0 does not initialize the error buffer, and cases have been reported where a curl download failed without the error buffer being set. This was the case on older systems that did not yet have curl 7.60.0, and caused random garbage to be printed.
0-initialize the buffer and check whether the buffer has a useful message before returning it. Generate a substitute message using `curl_easy_strerror()` from the returned error code if the error buffer is not set.
Closes: https://trac.macports.org/ticket/60581
=> pextlib1.0: init err buffer, use err code if empty

aclocal.m4, configure
Some of our vendored dependencies are not reconfigure-safe without a distclean when changing, for example, `--prefix`. Specifically, this applies to Tcl, which does not recompile some of the files that contain the hardcoded prefix.
This leads to incorrect behavior when such a reconfigured MacPorts build directory is installed – the bundled Tcl interpreter may end up loading its packages from the previously configured `--prefix`.
Avoid this by always running `make distclean` in the build directory before running configure, but ignoring any errors, e.g. if the tree was not yet configured, or no distclean target exists in the Makefile.
See https://github.com/macports/macports-base/pull/79 and https://github.com/macports/macports-base/pull/80 for previous discussion of the issue.
=> aclocal.m4: Run distclean before config in subdirs

src/port1.0/portconfigure.tcl
only macports-clang-5+ clang compilers will accept macports-libstdc++
closes: https://trac.macports.org/ticket/59717
Presently, when a build calls for cxx_standard 2011, base will try to use clang-3.4 or clang-3.7 on PPC and on Intel if defaults are not to libc++.
This always fails, and either tries to call in libcxx on PPC (fails) or tries to send ```-stdlib=macports-libstdc++``` to clang 3.4 or clang-3.7 (fails).
=> portconfigure.tcl: use clang5+ for cxx11+ if not libc++

src/macports1.0/macports.tcl, src/macports1.0/tests/macports.test
Fix shellescape to work on Tiger
Closes: https://trac.macports.org/ticket/56626
The previous code relied on the fact that we use `sh` for `system` and `sh` is supposed to be a POSIX shell but on Tiger it isn't; Leopard was the first POSIX compliant Mac OS X version
=> Fix shellescape to work on Tiger

src/darwintracelib1.0/access.c, src/darwintracelib1.0/close.c, src/darwintracelib1.0/darwintrace.c, src/darwintracelib1.0/darwintrace.h, src/darwintracelib1.0/dup2.c, src/darwintracelib1.0/mkdir.c, src/darwintracelib1.0/open.c, src/darwintracelib1.0/proc.c, src/darwintracelib1.0/readdir.c, src/darwintracelib1.0/readlink.c, src/darwintracelib1.0/rename.c, src/darwintracelib1.0/rmdir.c, src/darwintracelib1.0/stat.c, src/darwintracelib1.0/unlink.c
Static initializers have no defined order in which they are run; interposed functions, however, take effect at program initialization. In some cases, our interposed functions would be called by libSystem's constructors and prior to *our* constructors, and this would lead to crashes in trace mode as we would be in an uninitialized state. All our interposers now immediately delegate to their interposees until the are sure initialization has been performed.
=> Do not interpose functions before initialization

src/port1.0/portconfigure.tcl
Currently MacPorts base considers clang 318 to be new enough to support C11. However in https://trac.macports.org/ticket/58919 fontforge failed to build because:
```
scripting.c:10698:1: error: unknown type name '_Noreturn'
```
This predated the existence of `compiler.c_standard` so clang < 318 was manually blacklisted, but this was not enough; it was fixed by blacklisting clang < 500.
Similarly in https://trac.macports.org/ticket/59066 it was determined that ipmitool requires C11 and `compiler.c_standard 2011` was added, but [this still fails to build](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/24322/steps/install-port/logs/stdio):
```
/opt/local/include/openssl/crypto.h:322:1: error: unknown type name '_Noreturn'
```
This PR proposes changing the minimum clang …
=> Require clang >= 500 for C11

src/port1.0/portstartupitem.tcl, src/port1.0/tests/portstartupitem.test
This allows multi-command start, stop and init values to work and allows executable values with arguments to work and gives the startupitems keyword feature parity with the older startupitem keywords.
Unfortunately it is also a change in syntax for existing users of the start, stop, init and executable keys of the startupitems keyword if the values of those keys contain whitespace. Additional quoting is now required.
See my question on the mailing list:
https://lists.macports.org/pipermail/macports-dev/2020-June/041973.html
Fortunately the list of affected ports using this syntax is small. The only affected ports I found are:
* [adblock2privoxy](https://github.com/macports/macports-ports/blob/master/www/adblock2privoxy/Portfile#L107-L139)
* …
=> Don't add extra quoting to startupitems key values

src/port/portindex.tcl
This commit adds a flag `-x` (for extended mode) which will allow to include more details in the Portindex, like notes, variant description etc.
**Why is this needed?**
We are trying to add variant `description` and port `notes` to the ports webapp. By faking the platform (`portindex -p`), we generate portindex for the latest MacOS and store it in the database. But the server and docker both run Linux, and hence the local ports tree is different from that generated by `portindex -p`. This renders `port variants` and `port notes` commands displaying incomplete/inconsistent results.
In addition to this, an extended portindex would also simplify the process of updating the database. We would be able to follow a single route, instead of three (which is being done right now).
=> Portindex: Add extended mode

src/port1.0/portsandbox.tcl, src/port1.0/portutil.tcl
Some Xcode builds will fail when /opt is on a separate volume. The nature of the errors vary, for example `tiffutil` will frequently fail. They're all permission-related errors, though.
Looking at the system logs, I noticed this:
```
localhost kernel[0]: (Sandbox) Sandbox: tiffutil(99434) deny(1) file-write-create /opt/.TemporaryItems/folders.502/TemporaryItems/(A Document Being Saved By tiffutil)
```
To address this, I added some code that should detect the mountpoint for `${prefix}`, and add its `.TemporaryItems` to the allowed directories.
It's worth noting that I haven't tested this in the normal setup; the code _ought_ to work, but I'd appreciate the confirmation!
=> sandbox: handle /opt/local on separate mountpoint

src/cregistry/entry.c
When the registry fails to deactivate or unmap a file, say which file it is.
See: https://trac.macports.org/ticket/61154
=> Improve deactivate/unmap failure error message

src/port/port.tcl
notes: add UI_PREFIX to port name messages; hide them with -q
This makes 'port notes installed' much more useful since you can more
easily distinguish actual notes.
An example:
```
$ ./port.sh notes maven\* and installed
--->  maven3 has the following notes:
To make maven 3.6.3 the default, please run
sudo port select --set maven maven3
--->  maven_select has no notes.
```
=> notes: add UI_PREFIX to port name messages; hide them with -q

src/port1.0/portdestroot.tcl
This allows ports to customize their launchd plists during the destroot phase. It also makes it easier for a developer to debug launchd plists since now the entire destroot phase doesn't need to be completed before the launchd plists are created.
Closes: https://trac.macports.org/ticket/60653
=> Make startupitems before destroot phase, not after

src/port1.0/fetch_common.tcl
The goal is to prevent a very large number of (ping) processes from being spawned all at the same time since that can cause the computer to become nonfunctional until it is restarted.
See https://trac.macports.org/ticket/60509#comment:9
The limit of 50 may not be right; we could pick a different limit.
=> Ping no more than 50 hosts per invocation

src/port1.0/portstartupitem.tcl
This PR makes the following options available to Portfiles:
```
startupitem.user
startupitem.group
```
With these, ports can now specify the user and group that launchd will run the port's daemon process under.  These will create `<UserName>` and `<GroupName>` entries, respectively, in the launchd plist file. Per @ryandesign's [comment](https://github.com/macports/macports-ports/pull/7938#issuecomment-667800864), these options have been available in [launchd since 10.4](https://www.manpagez.com/man/5/launchd.plist/osx-10.4.php).
This was tested manually.  I wanted to check this in with proper tests, but was not having much success as I don't have enough of an understanding of the MacPorts internals.
=> portstartupitem: add startupitem options so that ports can specify the user and group to run a launchd service as

aclocal.m4, configure
Using '==' with 'test' is not part of the POSIX shell specification, and 'dash' doesn't support it.
=> configure: remove a bash-ism in daemondo check

src/port1.0/portconfigure.tcl
…by revising approach from macports/macports-base#161
Fixes: https://trac.macports.org/ticket/61418
Untested; I currently am not using macports-base from git, nor an old-enough macOS version where this would be applicable.
=> restrict compiler for C++14 and thread-local storage

src/darwintracelib1.0/darwintrace.h
Variable `__darwintrace_initialized` was defined in `darwintrace.h`, rather than just a declaration; this makes the variable failed to function as intended (every translation unit that uses this header will have its own independent variable), and causes a link error when associated object files are compiled by GCC.
```
gcc-10 -dynamiclib -g -O2 -std=c99 -Wextra -Wall   -fPIC -arch x86_64  -Wl,-single_module access.o close.o darwintrace.o dup2.o mkdir.o open.o proc.o readdir.o readlink.o rename.o rmdir.o sip_copy_proc.o stat.o unlink.o -o darwintrace.dylib  -arch x86_64 -install_name /opt/ports/libexec/macports/lib/darwintrace1.0/darwintrace.dylib  
duplicate symbol '___darwintrace_initialized' in:
access.o
rmdir.o
duplicate symbol '___darwintrace_initialized' in:
access.o
close.o
... …
```
=> darwintracelib: variable '__darwintrace_initialized' was defined in header causing duplicated symbol in link time

doc/Makefile.in
MacOS X 10.4 has this version of GNU Make; MacOS X 10.5 to current provides version 3.81, which has a working 'and' function.
I honestly don't know if this is the best solution, but it works robustly in my testing on 10.4, 10.5, 10.12, and 11.3-beta. The 3 latter have GNU Make version 3.81, while the first has 3.80 & thus this issue.
=> Replicate make 'and' function for GNU Make 3.80

src/cregistry/entry.c
When an SQLite call returned one of the extended result codes (see https://sqlite.org/rescode.html#extended_result_code_list), the existing switch/case did not handle that, `errPtr` remained uninitialized, and following code crashed with a segmentation fault.
Avoid this by handling the extended result codes just like we're handling `SQLITE_ERROR`. Additionally, default-initialize the `errPtr` structure to avoid crashes in the future.
This manifested itself when attempting to uninstall ports from a database that returned `SQLITE_CORRUPT_INDEX` (779).
=> cregistry: Avoid segfault on extended result codes

doc/portfile.7
`use_automake` and `use_autoconf` were already in there, but `use_autoreconf` got left out somehow.
=> Add use_autoreconf option to portfile man page

src/port1.0/portconfigure.tcl
Triggered by a discussion at
https://github.com/macports/macports-ports/pull/7243
The clang blacklisting is currently allowing some versions on 10.13 (Xcode 9/10) that are either missing std::optional or for which the implementation is incomplete or broken.
Consider the basic test application, using `std::optional`
```
> cat test.cpp
#include <optional>
int main() {
std::optional<int> i = 0;
return i.value();
}
```
on macOS 10.13 with Xcode 9.4.1 this fails to build with
```
> clang++ -std=c++17 ./test.cpp
./test.cpp:1:10: fatal error: 'optional' file not found
#include <optional>
^~~~~~~~~~
1 error generated.
> clang++ --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: …
```
=> Fix c++17 compiler selection to blacklist incomplete mac10.13 versions

src/port1.0/portconfigure.tcl
(cherry picked from commit e641f42a9f6d93e1768bd91785d19467c30ddb02)
=> Fix c++17 compiler selection for macOS10.13

vendor/patches/tcl/fix-unsafe-buffer-lifetime.patch, vendor/tcl8.5.19/generic/tclIO.c
An old bug in Tcl was exposed by an optimization in LLVM Clang 13: see https://core.tcl-lang.org/tcl/info/24b9181478 and https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258392
I have not attempted to observe the issue or verify this patch myself, but would suggest it be applied before this eventually becomes a more widespread issue when MacPorts base is compiled with LLVM Clang 13 and future versions of Xcode Clang derived from it.
=> Fix Tcl bug 98af80f133: unsafe buffer lifetime

src/machista1.0/Makefile.in
On macOS 11, `-nostdlib` no longer works:
```
ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
```
We'd have to `-lSystem` to fix this, at which point `-nostdlib` no longer makes sense, so we might as well drop it. This may break tests on systems where compiling an (i386, x86_64) fat binary is not possible, but this is preferable to failure to build on modern macOS.
=> machista1.0: Fix test copilation on macOS 11

src/pextlib1.0/sip_copy_proc.c
On newer versions of macOS, Apple's implementation of `copyfile(3)` no longer restores the file's modification time when copying a SIP-protected file with `COPYFILE_STAT` (or `COPYFILE_ALL`, which should include `COPYFILE_STAT`). I have not tested whether this is a general problem with `copyfile(3)`, or just a problem when copying SIP-protected files.
Because `lazy_copy()` uses the destination file's mtime to determine whether a new copy of the file is needed, this meant that recently every single invocation of `lazy_copy()` did in fact make a new copy of the file. This caused trace mode to jump to much higher overhead between 6 and 9 times of the normal runtime.
Switch `copyfile(3)` to explicitly not copying the file's stat information and invoke `fchmod(2)` and `futimes(2)` after the …
=> pextlib1.0: Fix mtime restore in lazy_copy()

src/darwintracelib1.0/darwintrace.c, src/darwintracelib1.0/proc.c
Check for malloc() and read() errors.
=> darwintracelib1.0: check return value before use

src/cregistry/entry.c
with the necessary evil of `goto`
=> cregistry: replace nested statements with a loop

src/macports1.0/macports.tcl, src/macports1.0/sysctl.c
I'm pretty sure that I shouldn't use exec here, so any suggestions are appreciated :)
`sysctl` works slightly different on Linux, and so [`nproc`](https://man7.org/linux/man-pages/man1/nproc.1.html) was chosen to determine the number of processing units. Since `sysctl` might work on some BSDs as well as Darwin, it was left in a default `else` statment.
```
> /sbin/sysctl -n hw.activecpu 
sysctl: cannot stat /proc/sys/hw/activecpu: No such file or directory
```
```
> nproc --all
4
```
=> Fix sysctl implementation on non-Darwin

.github/workflows/coverage.yml, .github/workflows/main.yml
See https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/.
=> ci: Remove deprecated macOS 10.15 runner

src/port1.0/portlint.tcl
Resolves https://trac.macports.org/ticket/61980
@ryandesign
=> lint --nitpick: ignore lines python.versions, ruby.branch(es)?

src/macports1.0/macports.tcl
Whilst running MacPorts on a Raspberry Pi with an armv7l processor, I noticed that MacPorts set the incorrect `os_arch`.
This PR aims to improve MacPorts support on some more architectures by setting the correct `os_arch`. For a given architecture, the new functionality is:
- `Power Macintosh` and anything that begins with `ppc` is set as `powerpc`.
- ` i386`-`i786` and `x86_64` is mapped to `i386`.
- Any architecture that begins with `arm` or `aarch` will be mapped to `arm`.
Closes: https://trac.macports.org/ticket/64863
=> Set correct `os_arch` on additional archs

src/port1.0/portconfigure.tcl
https://github.com/macports/macports-base/commit/ebd226139d5ba8389367606761658ad0e3bb5cce
Added support for -stdlib with gcc10+, but neglected the fact this is not available on PPC.
See also https://trac.macports.org/ticket/66246
=> Do not pass -stdlib with gcc 10+ in PPC builds

.github/workflows/main.yml
To test that MacPorts builds and installs on non-Darwin, I thought that it would be useful to introduce an Ubuntu GitHub actions runner.
This is especially important since the ports.macports.org machine runs MacPorts on a linux distro.
Some of the tests fail on non-Darwin, so they are disabled for now. The most important part is checking that the build itself succeeds.
=> ci: Add ubuntu runner

src/port1.0/portconfigure.tcl
Compiler support has I think reached a level it make sense to add as a known standard.
As always, support is a gradual process with compilers. The versions here are a preliminary estimate of when the compilers first support the *primary* c++20 features, which of course is a bit subjective.
=> Add 2020 as known c++ standard

doc/portfile.7
Document keyword `configure.sdkroot`:
```
configure.sdkroot
The path to the macOS SDK to build against.
Type: optional
Default: Automatically set by MacPorts; varies by macOS release, whether Xcode installed, etc.
Example:
configure.sdkroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
```
Note that this keyword is already documented in the MacPorts Guide, so no updates are needed for the latter.
=> manpages: portfile: document keyword configure.sdkroot

doc/portfile.7
Add info for keywords `startupitem.user` and `startupitem.group`, which are presently undocumented:
```
startupitem.user
Run the daemon via the specified user.
Type: optional
Default: none
Values: username
Example:
startupitem.user my_daemon_username
startupitem.group
Run the daemon via the specified group.
Type: optional
Default: none
Values: groupname
Example:
startupitem.group my_daemon_groupname
```
If anyone would like to add/change the description, please speak up ASAP. Otherwise let's merge this, and at least ensure they're included in our documentation. (We can always refine this later, if folks want to add more.)
Corresponding PR, for the MacPorts Guide:
[PR 59 - guide: startupitem: document keywords startupitem.user/startupitem.group](https://github.com/macports/macports-guide/pu …
=> manpages: portfile: document keywords startupitem.user/startupitem.group

doc/macports.conf.in
When some parts of the path in `ccache_dir` are symlinks, sandbox violation errors occur. Added a notice in macports.conf.
=> macports.conf: Add an important note on ccache_dir

src/darwintracelib1.0/darwintrace.c, src/darwintracelib1.0/readdir.c, src/machista1.0/Makefile.in, src/machista1.0/libmachista.c, src/pextlib1.0/sip_copy_proc.c, src/pextlib1.0/tracelib.c
pextlib1.0/tracelib.c additionally had its own implementation, which is now no longer required since we have a centrally provided compatibility implementation.
machista1.0 did not yet use the compat implementation and thus probably did not work on operating systems that do not have strlcpy.
=> src: Add strl{cat,cpy},getline compat includes

src/darwintracelib1.0/darwintrace.c, src/darwintracelib1.0/darwintrace.h, src/darwintracelib1.0/proc.c, src/machista1.0/tests/empty.c, src/machista1.0/tests/libmachista-test.c, src/programs/daemondo/main.c, vendor/patches/tcl/build-strict-prototypes.patch, vendor/tcl8.6.13/generic/tclIO.c
Fixes: https://trac.macports.org/ticket/68320
=> Specify missing `void` parameter in function declarators

src/macports1.0/macports.tcl
Fixes: https://trac.macports.org/ticket/52700
=> rev-upgrade: skip weakly-linked

doc/portfile.7, src/port1.0/portstartupitem.tcl
Presently, when `startupitem.logfile` is specified, we add a plist entry for stdout logging (via `StandardOutPath`). But when errors and such occur - particularly due to a fatal startup issue - that output often goes to stderr.
Not capturing the latter, makes troubleshooting more difficult for users. Potentially requiring them to manually edit the plist file, to add an entry for `StandardErrorPath` themselves.
To ensure the user doesn't have to deal with that, add new option `startupitem.logfile.stderr`.
By default, it is set to `startupitem.logfile`. But the user can specify a different logfile, clear the value (to disable stderr logging), or set it independently of `startupitem.logfile` (if only stderr should be logged).
Fixes: https://trac.macports.org/ticket/67955
=> startupitem: add new option startupitem.logfile.stderr, for capturing stderr

doc/INTERNALS, doc/portfile.7, src/pextlib1.0/Pextlib.c, src/pextlib1.0/mktemp.c, src/pextlib1.0/mktemp.h, src/port1.0/portbump.tcl, src/port1.0/portutil.tcl
Possible alternative to #308. The two uses of `mkstemp` updated by this PR are the only ones I am aware of.
=> pextlib: Replace `mkstemp` with Tcl 8.6 `file tempfile`

doc/portfile.7
Add info for keyword `use_dmg`, which is presently undocumented:
```
use_dmg
Use a disk image (dmg).
Sets extract.suffix to ``.dmg''.
Sets extract.cmd to ``hdiutil''.
Sets extract.pre_args to ``attach''.
Sets extract.post_args to ``-private -readonly -nobrowse -mountpoint ...etc...''.
Type: optional
Example:
use_dmg yes
```
There's just one caveat, for `extract.post_args`: The number of arguments is significant, and things vary slightly due to necessary logic behind it:
```
set dmg_tmp_dir [exec mktemp -d -q "/tmp/mports.XXXXXXXX"]
set dmg_mount ${dmg_tmp_dir}/${worksrcdir}
file mkdir ${dmg_mount}
option extract.cmd [binaryInPath "hdiutil"]
option extract.pre_args attach
option extract.post_args "-private -readonly -nobrowse -mountpoint  ${dmg_mount} && [binaryInPath "cp"] -Rp …
```
=> manpages: portfile: document keyword use_dmg

src/port1.0/portlint.tcl
tcp_wrappers is one of the Portfiles that failed because of this, since get_variant_description expects three arguments, and only two were passed.
=> port1.0: Fix lint on portfiles with universal variant

standard_configure.sh
See: https://trac.macports.org/ticket/28001
=> Fix standard_configure.sh for out-of-source builds

src/cregistry/snapshot.c, src/cregistry/snapshot.h, src/cregistry/sql.c, src/macports1.0/restore.tcl, src/macports1.0/snapshot.tcl
Adding the lists of installed files to registry snapshots allows us to resolve path-based depspecs in the same way that a normal upgrade does. While this increases the size of the snapshots considerably, I think it's worth it for the correctness.
Lightly tested and confirmed to behave correctly with curl installed with its `path:share/curl/curl-ca-bundle.crt:curl-ca-bundle` dep satisfied by certsync.
=> Migration: snapshot installed files and use to resolve path-based deps

.github/workflows/main.yml
The macos-11 runner is slated for removal by the end of the month with brownouts scheduled to occur in the weeks leading up to that.
=> CI: Remove macos-11

src/macports1.0/selfupdate.tcl, src/port/port.tcl
Hi,
Here is a tiny suggestion about user interface.
People may want to know how many ports can be upgraded after the ports tree has been updated by `port selfupdate`.
This patch prints about numbers of outdated ports like this:
```
--->  Updating MacPorts base sources using rsync
MacPorts base version 2.8.1 installed,
MacPorts base version 2.8.1 downloaded.
--->  Updating the ports tree
--->  MacPorts base is already the latest version
The ports tree has been updated. To upgrade your installed ports, you should run
port upgrade outdated
2 ports are outdated. Run 'port outdated' to see them.
```
and when no installed ports are outdated will look like this:
```
--->  Updating MacPorts base sources using rsync
MacPorts base version 2.8.1 installed,
MacPorts base version 2.8.1 downloaded. …
```
=> selfupdate: Prints number of outdated ports after updating ports tree

src/port1.0/portstartupitem.tcl
This message or one of its prior wordings has been present ever since the startup item code was originally added in 3ffdaf3 in 2005.
I presume the purpose of this message was to inform the user that a startup item existed for this port. It no longer accomplishes that purpose because it only appears during the destroot phase which most users will not see because they install pre-built archives instead of building from source. Meanwhile a better message in the form of notes that display at the end of installation, regardless of whether it was from source or via pre-built archive, was added in 6faf3f8 in 2018.
Originally, the startup item was created at the end of the destroot phase, so users would first see the "Staging into destroot" message, followed by a delay as staging occurred, …
=> Remove "Creating launchd control script" message

src/macports1.0/snapshot.tcl
- snapshot: Report match in --diff if there are no changes  
The user experience of `sudo port snapshot --diff $id --all` just printing nothing is not great. Improve this by explicitly printing a success message if there are no changes.
- snapshot: Handle errors with unknown snapshot IDs
=> snapshot: UX improvements

src/pextlib1.0/curl.c
This command can be useful for debugging connectivity issues  when Pextlib becomes upgradeable via a dedicated port and uses a libcurl that is also installed through its own dedicated port.
The command returns a Tcl dict containing information about the libcurl version that Pextlib was built against as well as the libcurl it is currently running against; a simplified equivalent of `curl --version`.
Obtaining a list of names of available feature is possible only since curl v7.87.0 so this information will probably be replaced with a simple feature mask in the Pextlib build installed by the MacPorts installer on most older Darwin versions.
See trac ticket #51516
=> Add a `curl version` Tcl command to Pextlib.

src/programs/cp/cp.c
This is intended to fix https://trac.macports.org/ticket/70897 but I could not reproduce the problem so I don't know if this fixes it.
=> cp: NULL-terminate new_argv and use simpler execv instead of execve

src/pextlib1.0/curl.c
Fix sync warning about checking update failed due to rejected connection without a user-agent on some mirrors.
The user-agent for curl isnewer is conform to https://trac.macports.org/ticket/40319.
=> Set a user-agent for curl isnewer.

src/pextlib1.0/system.c
Linux requires stdio.h for getline(3), and fails without it. We ship a getline.h compat implementation, but that doesn't get included unless HAVE_GETLINE isn't defined, which isn't the case on Linux.
=> pextlib1.0: Sort includes, add stdio.h for getline(3) on Linux

src/port1.0/port_autoconf.tcl.in, src/port1.0/porttrace.tcl
Access would previously be allowed, too, because these files are not installed by a MacPorts port. They did generate a warning, though, which is not necessary. Adding an explicit whitelist entry silences them.
=> port1.0: Allow accessing clonebin in trace mode

src/darwintracelib1.0/darwintrace.c
Don't call abort() just because we can't read a symlink. Instead, ignore the error and let it bubble up to the build that attempted the read.
=> darwintrace: Don't fail on unreadable symlinks

src/programs/cp/cp.c
`execve()` expects the args to be in writable memory, so copy them using `strdup(3)`.
=> programs/cp: Fix pointer cast warning

src/port1.0/portsandbox.tcl
Grant access to Xcode's caches, as well as the `worksrcpath`. If the ports DB or the build directory[1] are on other volumes, grant access to the `TemporaryItems` directory of that volume as well. Grant permission to create jobs.
[1]: Since I have 96 GiB of RAM, I have placed the build directory on a tmpfs to avoid wear and tear on my SSD. I just hope that no port needs more than 48 GiB to build...
=> Give Xcode more permissions in the sandbox.

.gitignore, config.guess, config.sub, configure, configure.ac, install-sh, src/port/Makefile.in, src/port/port-tclsh.in
Tcl attempts to determine the path of its standard library relative to the path of its binary, but does not expand symlinks when doing that. `port-tclsh` thus inadvertently uses libraries from a MacPorts-installed Tcl rather than the copies shipped with MacPorts.
See: https://trac.macports.org/ticket/64507
Closes: https://trac.macports.org/ticket/72359
=> src/port: Replace port-tclsh symlink with script
