- src/port/portindex.tcl
This avoids expanded values for ${prefix} in the PortIndex.
Closes: https://trac.macports.org/ticket/53169
See: https://trac.macports.org/ticket/17182
> portindex: Restore special $prefix handling

- doc/port-reclaim.1.txt
No changes are made to the files until the user selects them after running it.
> Explain that interactions, and no initial change.

- configure
- configure.ac
- src/port1.0/port_autoconf.tcl.in
- src/port1.0/portstartupitem.tcl
Macports supports Tiger and later which all have launchd.
see https://trac.macports.org/ticket/36770
> Remove configure checks for launchd

- doc/port.1
- doc/port.1.txt
Closes: https://trac.macports.org/ticket/54037
> doc: list port reclaim in port.1

- src/port/portindex.tcl
https://trac.macports.org/wiki/Meetings/MacPortsMeeting2018/GSoC#Hackingsessionideas
> portindex: return >0 value if some ports failed

- src/port1.0/portpatch.tcl
closes https://trac.macports.org/ticket/52445
> Add the ability to handle xz patch files

- doc/macports.conf.in
- src/macports1.0/macports.tcl
- src/registry2.0/portimage.tcl
This is a continuation from #45.
Ticket: https://trac.macports.org/ticket/36560
> Apply HFS+ compression on archive extraction

- configure
- configure.ac
macOS 10.13.0-10.13.4 are outdated.
> configure: Update macOS version checks

- src/port1.0/portutil.tcl
- src/port1.0/tests/portutil.test
Instead of having to use system(), use touch -W dir file
See https://trac.macports.org/ticket/53730
> port: add -W to touch command

- src/package1.0/portarchivefetch.tcl
Closes: https://trac.macports.org/ticket/57717
> Fix archive_site_local

- src/port1.0/portutil.tcl
The previous behaviour involved a complicated regex, made it very
difficult to set an environment variable value including quote
characters, and was responsible for many cases of variables being in
foo.env but not actually appearing in the environment.
Portfiles will need to be reviewed for cases of writing `foo.env-append VAR="foo bar"` since that adds two elements to foo.env, `VAR="foo` and `bar"` (double quotes only have a special meaning to Tcl if they appear at the start of a word).
> Treat command.env as a list

- config.guess
- config.sub
These are primarily non-functional changes for us but reduce the diff in
the future should we ever need to update again.
> auto*: bump config.guess and config.sub to 2019-03-04

- doc/Makefile.in
- doc/port-bump.1
- doc/port-bump.1.txt
Create the port bump (1) manpage and enable port-bump.1
See: https://github.com/satraul/macports-base/issues/1
> doc: Document port bump

- doc/portfile.7
see https://trac.macports.org/ticket/56035
> doc: Add use_lzip documentation

- doc/port-mirror.1.txt
see https://trac.macports.org/ticket/56025
> Add note that ports with license NoMirror will not be mirrored

- src/macports1.0/macports.tcl
- src/port1.0/portutil.tcl
Also improve Xcode not installed message
> Remove xcodebuild warning

- src/macports1.0/diagnose.tcl
on older systems -p is not recognized
> use xcode-select -print-path

- src/macports1.0/macports.tcl
Temporary fix for Linux not working
References: http://trac.macports.org/ticket/58497
> Only check OS/platform on MacOS

- doc/portfile.7
this PR add `variable-replace` extension to portfile(7)
> add variable-replace to portfile(7)

- src/port1.0/portconfigure.tcl
See https://github.com/macports/macports-ports/commit/733501b705d4bd94a0b950f5f019366051d078db
> update list of Clang compilers

- src/port1.0/fetch_common.tcl
Process ping output using Tcl rather than by spawning grep and cut processes.
This is one of several steps that may help alleviate https://trac.macports.org/ticket/60509.
> Process ping output without using grep or cut

- src/pextlib1.0/curl.c
- src/pextlib1.0/tests/curl.tcl
#188 and #186 are bugfixes and thus relevant for the release-2.6 branch. Cherry-pick the relevant commits to release-2.6.
> Cherry-pick #188 and #186 to release-2.6

- src/port1.0/portutil.tcl
`adduser` and `addgroup` (invoked by the `add_users` statement in `handle_add_users`) elevates its privileges, but does not always drop them again. Specifically, this could happen if a user or group already existed, in which case `adduser` did elevate to root, but not drop back to the macportsuser again.
This can cause files to be created with incorrect permissions, which can then cause permissions problems in subsequent phases.
Closes: https://trac.macports.org/ticket/50918
> port1.0: Ensure adduser drops privs in all cases

- ChangeLog
- src/port1.0/portutil.tcl
> release2.6: port1.0: Ensure adduser drops privs in all cases

- src/port/port.tcl
Closes: https://trac.macports.org/ticket/61083
> Fix port info --depends with multiple ports

- src/port1.0/portconfigure.tcl
On macOS 11, implicit function declarations are now errors by default. This may affect configure checks and actually cause software to compile differently without us knowing.
Add a post-configure check that scans any `config.log` files in `${configure.dir}` for indicators of such problems and warn about them, so they will not go unnoticed.
Provide a way to disable this functionality in a Portfile, in case the maintainer did verify that those are false positives.
> port1.0: configure: Add check for implicit decls

- HACKING
Inclusive language helps to avoid discouraging contributions from people belonging to marginalised groups in technology.
> Replace gendered terms in HACKING with gender-neutral ones

- src/port1.0/portbuild.tcl
Currently `portbuild::build_getjobsarg` returns an empty string if `use_parallel_build no` is set. 
Ninja though defaults to enabling parallel builds so to disable them you have to explicitly pass `-j1`. 
This PR implements this.
> Fix 'use_parallel_build no' builds with ninja which requires -j1 to disable parallelism

- src/macports1.0/get_systemconfiguration_proxies.c
- src/pextlib1.0/Pextlib.c
- src/pextlib1.0/sip_copy_proc.c
Fix leaks found in static code analysis.
> Fix memory and resource leaks

- src/cregistry/README.sqlext
See also commit 4664a4a6c680ec55387f7c3ecd94102588a8f299.
> cregistry: add build instruction to README.sqlext

- .github/workflows/coverage.yml
- src/port1.0/tests/portutil.test
Generate an llvm-cov coverage report for C code.
> ci: add coverage report workflow

- vendor/patches/tcl/configure-implicit-declarations.patch
- vendor/tcl8.6.12/unix/configure
- vendor/tcl8.6.12/unix/tcl.m4
As already done in macports/macports-ports@45a8c4c63e9b
> tcl: use upstream approach in patch

- src/port1.0/portconfigure.tcl
Closes: https://trac.macports.org/ticket/67504
> Update implicit func decl detection for new clangs

- src/programs/daemondo/main.c
As recommended by e.g. https://wiki.sei.cmu.edu/confluence/display/c/DCL15-C.+Declare+file-scope+objects+or+functions+that+do+not+need+external+linkage+as+static
> daemondo/main.c: use static

- src/macports1.0/macports.tcl
- src/port/port.tcl
- src/registry2.0/portimage.tcl
See the commit messages for more detailed descriptions:
```
d4461665c registry2.0: Improve extract progress bar
818d5d019 registry2.0: Enable progress bar for deactivation
63a832960 port: Tolerate progress bars where the 'start' action wasn't called
5ee0e4518 registry2.0: Enable progress bar for activation
```
> registry2.0: Enable progress bar for activation & deactivation

- .github/workflows/main.yml
As suggested by @raimue in a comment on 55d389d5.
> CI: Use standard_configure.sh

- src/port1.0/portconfigure.tcl
Check for `-Wimplicit-int` and `-Wincompatible-function-pointer-types` warnings in configure logs because llvm.org clang 16 and the latest Apple clang consider those to be errors.
Closes: https://trac.macports.org/ticket/70017
-----
This is an initial attempt that works but it could possibly be improved. There is some code duplication with the implicit function declaration checks. And since function names are not involved in these warnings, no information other than the configuration log file the warning appeared in is shown. Maybe showing how many occurrences were found in each log file would be useful, though that improvement might also be helpful in the implicit function declaration checks.
> Check for more warnings in configure logs

- doc/port.1
- doc/port.1.txt
See https://lists.macports.org/pipermail/macports-users/2024-October/053107.html.
> doc: Document migrate/restore/snapshot in port(1)

- src/port1.0/portclean.tcl
- src/port1.0/portutil.tcl
Now creating an 8-character build dir for each subport directly under `${portdbpath}/build`, using `mkdtemp` to ensure uniqueness, and creating a symlink from the traditional location based on the full path to the portdir.
Closes: https://trac.macports.org/ticket/70539
> Use shorter build paths
